#!/bin/bash

echo " "
echo " "
echo "Deseja criar uma senha para o usuário root?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read root

case "$root" in
 s|S|y|Y|"")
 sudo passwd root
 clear
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -f
sudo apt-get autoremove
sudo apt-get clean
sudo apt-get autoclean

clear

echo " "
echo " "
echo "Deseja instalar o drive proprietário de vídeo?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read resposta

case "$resposta" in
 s|S|y|Y|"")
 lspc1 | grep vga
 echo "Insira o nome do drive vga listado: " ; read driver
 sudo apt search $driver
 echo "Insira o nome do pacote a ser instalado: " ; read pacote
 sudo apt install $pacote
 sudo apt-get install -f
 sudo update-initramfs -u
 sudo reboot
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac


echo " "
echo " "
echo "Pesquisando aplicativos no repositório para a instalação. Aguarde..."
sleep 5

sudo apt search xinit
sudo apt search slim
sudo apt search openbox
sudo apt search obconf
sudo apt search lxappearance
sudo apt search wicd
sudo apt search wicd-curses
sudo apt search pulseaudio
sudo apt search pavucontrol
sudo apt search pcmanfm
sudo apt search conky
sudo apt search xarchiver
sudo apt search feh

clear

echo " "
echo " "
echo "Iniciando a instalação de aplicativos do repositório. Aguarde..."
sleep 5

sudo apt install xinit
clear
sudo apt install slim
clear
sudo apt install openbox
clear
sudo apt install obconf
clear
sudo apt install lxappearance
clear
sudo apt install wicd
clear
sudo apt install wicd-curses
clear
sudo apt install pulseaudio
clear
sudo apt install pavucontrol
clear
sudo apt install pcmanfm
clear
sudo apt install conky
clear
sudo apt install xarchiver
clear
sudo apt install feh
clear

echo " "
echo " "
echo "Qual navegador de internet deseja instalar?"
echo -n "Digite (0)Chromium (1)Firefox-repositório (2)Firefox-última-versão (3)Google Chrome 64 bits. Tecle Enter para confirmar: " ; read browser

case "$browser" in
 0|"")
 sudo apt search chromium-browser
 sudo apt-get -y install chromium-browser
 clear
 ;; 
 1)
 sudo apt search firefox
 sudo apt-get -y install firefox
 clear
 ;;
 2)
 if [ $(uname -m) == "x86_64" ]; then 
 wget "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=pt-BR" -O firefox.tar.bz2; else 
 wget "https://download.mozilla.org/?product=firefox-latest&os=linux&lang=pt-BR" -O firefox.tar.bz2; fi
 sudo tar -jxvf firefox.tar.bz2 -C /opt/
 sudo mv /opt/firefox*/ /opt/firefox
 sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
 rm firefox.tar.bz2
 clear
 ;;
 3)
 wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 sudo dpkg -i google-chrome-stable_current_amd64.deb
 sudo apt-get install -f
 rm google-chrome*.deb
 clear
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac


echo " "
echo " "
echo "Deseja instalar o editor de texto?"
echo -n "Digite (0) leafpad (1) geany (2) gedit. Tecle Enter para confirmar: " ; read edit

case "$edit" in
 0|"")
 sudo apt search leafpad
 sudo apt-get install leafpad
 clear
 ;; 
 1)
 sudo apt search geany
 sudo apt-get install geany
 clear
 ;;
 2)
 sudo apt search gedit
 sudo apt-get install gedit --no-install-recommends --no-install-suggests
 clear
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac

clear

echo " "
echo " "
echo "Deseja instalar o reprodutor de mídia vlc?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read vlc

case "$vlc" in
 s|S|y|Y|"")
 sudo apt search vlc
 sudo apt-get install vlc --no-install-recommends --no-install-suggests
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac

clear

echo " "
echo " "
echo "Deseja desinstalar o driver de video nouveau?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read nouveau

case "$nouveau" in
 s|S|y|Y|"")
 sudo apt purge xserver-xorg-video-nouveau
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac

clear
#sudo apt remove uxterm xterm

echo " "
echo " "
echo "Deseja instalar o lxterminal?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; lxterm vlc

case "$lxterm" in
 s|S|y|Y|"")
 sudo apt search lxterminal
 sudo apt install lxterminal
 clear
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac

echo " "
echo " "
echo "Deseja instalar o suporte para impressora ou scanner?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read periferic

case "$periferic" in
 s|S|y|Y|"")
 sudo apt install lsb
 echo "O suporte para instalação de impressoras e scanners foi instalado."
 echo "Após a inicialização gráfica, instale os drivers mais recentes de acordo com o seu modelo."
 sleep 5
 clear
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac

echo " "
echo " "
echo "Deseja instalar programa xsane scanner?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read scanner

case "$scanner" in
 s|S|y|Y|"")
 sudo apt search xsane
 sudo apt search libsane-extras
 sudo apt search sane-utils
 clear
 sudo apt install sane-utils libsane-extras xsane
 sudo adduser $USER scanner
 ;;
 n|N)
 echo "Continuemos o procedimento de instalação de outros pacotes."
 sleep 5
 clear
 ;;
 *)
 echo "Opção inválida"
 ;;
esac

sudo apt-get install -f
sudo apt-get autoremove
sudo apt-get clean
sudo apt-get autoclean
