#!/bin/bash

sudo passwd root

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -f
sudo apt-get autoremove
sudo apt-get clean
sudo apt-get autoclean

echo " "
echo " "
echo "Deseja instalar o drive proprietário de vídeo?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read resposta

case "$resposta" in
    s|S|y|Y|"")
            lspc1 | grep vga
            echo "Insira o nome do drive vga listado: " ; read driver
            sudo apt search $driver
            echo "Insira o nome do pacote a ser instalado: " ; read pacote
            sudo apt install $pacote
            sudo apt-get install -f
            sudo update-initramfs -u
            sudo reboot
    ;;
    n|N)
            echo "Continuemos o procedimento de instalação de outros pacotes."
            sleep 5
            clear
    ;;
    *)
            echo "Opção inválida"
    ;;
esac


echo " "
echo " "
echo "Pesquisando aplicativos no repositório para a instalação. Aguarde..."
sleep 5

sudo apt search xinit
sudo apt search slim
sudo apt search openbox
sudo apt search obconf
sudo apt search lxappearance
sudo apt search wicd
sudo apt search wicd-curses
sudo apt search pulseaudio
sudo apt search pavucontrol
sudo apt search pcmanfm
sudo apt search conky
sudo apt search xarchiver
sudo apt search leafpad
sudo apt search feh
sudo apt search chromium-browser
sudo apt search firefox
sudo apt search lxterminal

clear

echo " "
echo " "
echo "Iniciando a instalação de aplicativos do repositório. Aguarde..."
sleep 5

sudo apt install xinit
sudo apt install slim
sudo apt install openbox
sudo apt install obconf
sudo apt install lxappearance
sudo apt install wicd
sudo apt install wicd-curses
sudo apt install pulseaudio
sudo apt install pavucontrol
sudo apt install pcmanfm
sudo apt install conky
sudo apt install xarchiver
sudo apt install leafpad
sudo apt install feh
sudo apt install chromium-browser
sudo apt install firefox
sudo apt install lxterminal

echo " "
echo " "
echo "Deseja instalar o editor de texto gedit?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read gedit

case "$gedit" in
    s|S|y|Y|"")
            sudo apt search gedit
            sudo apt-get install gedit --no-install-recommends --no-install-suggests
    ;;
    n|N)
            echo "Continuemos o procedimento de instalação de outros pacotes."
            sleep 5
            clear
    ;;
    *)
            echo "Opção inválida"
    ;;
esac

echo " "
echo " "
echo "Deseja instalar o reprodutor de mídia vlc?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read vlc

case "$vlc" in
    s|S|y|Y|"")
            sudo apt search vlc
            sudo apt-get install vlc --no-install-recommends --no-install-suggests
    ;;
    n|N)
            echo "Continuemos o procedimento de instalação de outros pacotes."
            sleep 5
            clear
    ;;
    *)
            echo "Opção inválida"
    ;;
esac

echo " "
echo " "
echo "Deseja desinstalar o driver de video nouveau?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read nouveau

case "$nouveau" in
    s|S|y|Y|"")
            sudo apt purge xserver-xorg-video-nouveau
    ;;
    n|N)
            echo "Continuemos o procedimento de instalação de outros pacotes."
            sleep 5
            clear
    ;;
    *)
            echo "Opção inválida"
    ;;
esac

#sudo apt remove uxterm xterm

echo " "
echo " "
echo "Deseja instalar o suporte para impressora ou scanner?"
echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read periferic

 case "$periferic" in
        s|S|y|Y|"")
            sudo apt install lsb
            echo "O suporte para instalação de impressoras e scanners foi instalado."
            echo "Após a inicialização gráfica, instale os drivers mais recentes de acordo com o seu modelo.
            sleep 5
            clear
            echo " "
            echo " "
            echo "Deseja instalar o programa xsane scanner?"
            echo -n "Digite (S)im ou (N)ão. Tecle Enter para confirmar: " ; read xsane
                case "$xsane" in
                    s|S|y|Y|"")
                    sudo apt search xsane
                    sudo apt search libsane-extras
                    sudo apt search sane-utils
                    clear
                    sudo apt install sane-utils libsane-extras xsane
                    sudo adduser $USER scanner
                ;;
                    n|N)
                    echo "Continuemos o procedimento de instalação de outros pacotes."
                    sleep 5
                    clear
                ;;
                    *)
                    echo "Opção inválida"
                ;;
                esac      
    ;;
    n|N)
            echo "Continuemos o procedimento de instalação de outros pacotes."
            sleep 5
            clear
    ;;
    *)
            echo "Opção inválida"
    ;;


sudo apt-get install -f
sudo apt-get autoremove
sudo apt-get clean
sudo apt-get autoclean
